import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { config } from '../config.js';
import { ProductMaster } from '../types.js';

const mobileSeedPath = path.resolve(
  config.repositoryRoot,
  'apps',
  'mobile',
  'src',
  'data',
  'productMaster.generated.ts',
);

async function main() {
  const raw = await readFile(config.outputJsonPath, 'utf8');
  const products = JSON.parse(raw) as ProductMaster[];
  const source = [
    "import { ProductMaster } from '@/features/products/productTypes';",
    '',
    '// This file is generated by services/product-importer. Do not edit by hand.',
    `export const generatedProductMasterSeed: ProductMaster[] = ${JSON.stringify(products, null, 2)};`,
    '',
  ].join('\n');

  await mkdir(path.dirname(mobileSeedPath), { recursive: true });
  await writeFile(mobileSeedPath, source, 'utf8');
  console.log(`[export:mobile-seed] exported ${products.length} products to ${mobileSeedPath}`);
}

void main();
